name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pages: write
  pull-requests: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'timerx.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Set secrets
        run: |
          echo "storeFile=${{ steps.decode_keystore.outputs.filePath }}" >> keystore.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> keystore.properties
          echo "keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" >> keystore.properties

      - name: Check
        run: ./gradlew bundle

      - name: Archive Android Debug AAB
        uses: actions/upload-artifact@v4
        with:
          name: Android Debug AAB
          path: androidApp/build/outputs/bundle/debug/androidApp-debug.aab
          if-no-files-found: error

      - name: Archive Android Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: Android release build
          path: androidApp/build/outputs/bundle/release/androidApp-release.aab

          if-no-files-found: error
