name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pages: write
  pull-requests: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 24
          check-latest: true
          distribution: zulu
          cache: gradle

      - name: Set local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 --decode > local.properties

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'hagah.jks'
          encodedString: ${{ secrets.KEY_STORE }}

      # TODO: https://github.com/kotest/kotest/issues/3598
      - name: Check
        run: ./gradlew check koverXmlReport --warning-mode all -x desktopTest -x iosSimulatorArm64Test

      - name: Archive Android-App lint
        uses: actions/upload-artifact@v4
        with:
          name: Android app lint
          path: composeApp/build/reports/lint-results-debug.html
          if-no-files-found: error

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: build/reports/kover/report.xml

          title: Code Coverage
          update-comment: true
          min-coverage-overall: 10
          min-coverage-changed-files: 80
          coverage-counter-type: LINE
