name: linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: publishing
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          check-latest: true
          java-version: 17
          cache: 'gradle'

      - name: Create local properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 --decode > local.properties

      - name: Create keystore
        run: echo "$LOCAL_PROPERTIES" | base64 --decode > local.properties
               - name: Decode Keystore
               id: decode_keystore
               uses: timheuer/base64-to-file@v1
               with:
                 fileName: 'hagah.jks'
                 encodedString: ${{ secrets.KEY_STORE }}

      - name: Create linux Deb
        run: ./gradlew packageDeb packageReleaseDeb packageRpm packageReleaseRpm

      - name: Archive Deb Debug
        uses: actions/upload-artifact@v4
        with:
          name: Deb-Debug
          path: composeApp/build/compose/binaries/main/deb/com.fergdev.hagah**.deb
          if-no-files-found: error

      - name: Archive Deb Release
        uses: actions/upload-artifact@v4
        with:
          name: Deb-Release
          path: composeApp/build/compose/binaries/main-release/deb/com.fergdev.hagah**.deb
          if-no-files-found: error

      - name: Archive Rpm Debug
        uses: actions/upload-artifact@v4
        with:
          name: Rpm-Debug
          path: composeApp/build/compose/binaries/main/rpm/com.fergdev.hagah**.rpm
          if-no-files-found: error

      - name: Archive Rpm Release
        uses: actions/upload-artifact@v4
        with:
          name: Rpm-Release
          path: composeApp/build/compose/binaries/main-release/rpm/com.fergdev.hagah**.rpm
          if-no-files-found: error
