name: OSX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pages: write
  pull-requests: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - name: Create local properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 --decode > local.properties

      - name: Create keystore
        run: echo "$LOCAL_PROPERTIES" | base64 --decode > local.properties
               - name: Decode Keystore
               id: decode_keystore
               uses: timheuer/base64-to-file@v1
               with:
                 fileName: 'hagah.jks'
                 encodedString: ${{ secrets.KEY_STORE }}

      - name: Build with Gradle
        run: ./gradlew packageDmg packageReleaseDmg packagePkg packageReleasePkg

      - name: Archive DMG Debug
        uses: actions/upload-artifact@v4
        with:
          name: DMG-Debug
          path: composeApp/build/compose/binaries/main/dmg/com.fergdev.hagah-**.dmg
          if-no-files-found: error

      - name: Archive DMG Release
        uses: actions/upload-artifact@v4
        with:
          name: DMG-Release
          path: composeApp/build/compose/binaries/main-release/dmg/com.fergdev.hagah-**.dmg
          if-no-files-found: error

      - name: Archive DMG Debug
        uses: actions/upload-artifact@v4
        with:
          name: PKG-Debug
          path: composeApp/build/compose/binaries/main/pkg/com.fergdev.hagah-**.pkg
          if-no-files-found: error

      - name: Archive DMG Release
        uses: actions/upload-artifact@v4
        with:
          name: PKG-Release
          path: composeApp/build/compose/binaries/main-release/pkg/com.fergdev.hagah-**.pkg
          if-no-files-found: error
