name: OSX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pages: write
  pull-requests: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - name: Set secrets
        run: |
          echo "storeFile=${{ steps.decode_keystore.outputs.filePath }}" >> keystore.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> keystore.properties
          echo "keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" >> keystore.properties
          echo "openAiApiKey=${{ secrets.OPEN_AI_API_KEY }}" >> keystore.properties

      - name: Build with Gradle
        run: ./gradlew packageDmg packageReleaseDmg packagePkg packageReleasePkg

      - name: Archive DMG Debug
        uses: actions/upload-artifact@v4
        with:
          name: DMG-Debug
          path: composeApp/build/compose/binaries/main/dmg/com.fergdev.hagah-**.dmg
          if-no-files-found: error

      - name: Archive DMG Release
        uses: actions/upload-artifact@v4
        with:
          name: DMG-Release
          path: composeApp/build/compose/binaries/main-release/dmg/com.fergdev.hagah-**.dmg
          if-no-files-found: error

      - name: Archive DMG Debug
        uses: actions/upload-artifact@v4
        with:
          name: PKG-Debug
          path: composeApp/build/compose/binaries/main/pkg/com.fergdev.hagah-**.pkg
          if-no-files-found: error

      - name: Archive DMG Release
        uses: actions/upload-artifact@v4
        with:
          name: PKG-Release
          path: composeApp/build/compose/binaries/main-release/pkg/com.fergdev.hagah-**.pkg
          if-no-files-found: error
