name: wasm

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pages: write
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: publishing
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          check-latest: true
          java-version: 17
          cache: 'gradle'

      - name: Set secrets
        run: |
          echo "storeFile=${{ steps.decode_keystore.outputs.filePath }}" >> keystore.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> keystore.properties
          echo "keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" >> keystore.properties
          echo "openAiApiKey=${{ secrets.OPEN_AI_API_KEY }}" >> keystore.properties

      - name: Build wasm
        run: ./gradlew wasmJsBrowserDistribution

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        if: github.ref == 'refs/heads/main'
        with:
          path: 'composeApp/build/dist/wasmJs/productionExecutable'

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
