name: wasm

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pages: write
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: publishing
    steps:
      - uses: actions/checkout@v5

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 24
          check-latest: true
          distribution: zulu
          cache: gradle

      - name: Set local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 --decode > local.properties

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'hagah.jks'
          encodedString: ${{ secrets.KEY_STORE }}

      - name: Build wasm
        run: ./gradlew wasmJsBrowserDistribution

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        if: github.ref == 'refs/heads/main'
        with:
          path: 'composeApp/build/dist/wasmJs/productionExecutable'

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
