name: windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          check-latest: true
          java-version: 17
          cache: 'gradle'

      - name: Create local properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        shell: bash
        run: echo "$LOCAL_PROPERTIES" | base64 --decode > local.properties

      - name: Build
        run: |
          ./gradlew packageExe packageReleaseExe packageMsi packageReleaseMsi --warning-mode all

      - name: Archive Exe Release
        uses: actions/upload-artifact@v4
        with:
          name: Exe-Release
          path: composeApp/build/compose/binaries/main-release/exe/com.fergdev.hagah**.exe
          if-no-files-found: error

      - name: Archive Exe Debug
        uses: actions/upload-artifact@v4
        with:
          name: Exe-Debug
          path: composeApp/build/compose/binaries/main/exe/com.fergdev.hagah**.exe
          if-no-files-found: error

# TODO fix msi
#      - name: Archive MSI Release
#        uses: actions/upload-artifact@v4
#        with:
#          name: MSI-Release
#          path: composeApp/build/compose/binaries/main-release/msi/com.ferdev.hagah**.msi
#          if-no-files-found: error
#
#      - name: Archive MSI Debug
#        uses: actions/upload-artifact@v4
#        with:
#          name: MSI-Debug
#          path: composeApp/build/compose/binaries/main/msi/com.ferdev.hagah**.msi
#          if-no-files-found: error
